server:
  port: 8082

hystrix:
  shareSecurityContext=true:

feign:
  hystrix:
    enabled=true:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_court
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
appDescription: "FoodCourt for Pragma BootCamp"
appVersion: "1.0.0"
